printStatsCron: 0 * * * * ?

logging:
  level:
    volkovandr: trace

bot:
  bot-user-name: curse-stats-test-bot
  greeting-message: Hello everybody, the curse-stats-bot is running!
  stats-message-template: User {user} cursed {cursesCount} times, his favorite curse is {favoriteCurse}!
  goodbye-message: Goodbye everybody, the curse-stats-bot is shutting down!
  replaceLetters:
    "[ё]": "е"
  curses:
    - fuck.*
    - shit.*
    - damn.*
    - cunt
    - bitch
    - черт.*


