package volkovandr.cursestatsbot.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties
class EnableConfigurationPropertiesConfiguration
